
        <a href="#" class="floating-button">Page Up</a>
        <footer>
            <div class="container">
                <div class="footer-content-wrapper">
                    <div class="col">
                        <a href="index.php" class="logo"><h2>NodeGenius</h2></a>
                    </div>
                    <div class="col">
                        <h3>About us</h3>
                        <p>
                            "Welcome to NodeGenius' About page! We're a passionate team with a deep love for web technology, thrilled to unveil the wonders of Node.js. Through our collaboration, we're crafting an immersive website to
                            illuminate the realm of Node JS."...
                            <a href="about.php" class="readmore">Read more</a>
                        </p>
                        <h3>Contact us</h3>
                        <p>
                            <a href="mailto:compsysproj@gmail.com">compsysproj@gmail.com</a>
                        </p>
                    </div>
                    <div class="col">
                        <h3>Explore more</h3>
                        <ul class="page-links">
                            <li><a href="index.php">Home</a></li>
                            <li><a href="overview.php">Overview</a></li>
                            <li><a href="quiz.php">Quiz</a></li>
                            <li><a href="enhancements.php">Updates</a></li>
                            <li><a href="about.php">About</a></li>
                            <li><a href="contact.php">Contact</a></li>
                            <li><a href="contact.php">Contact</a></li>
                        </ul>
                    </div>
                </div>

               <!-- <h3>Tutor's email</h3>
                <p class="tutors-email">
                    <a href="mailto:compsysproj@gmail.com">compsysproj@gmail.com</a>
                </p> -->
            </div>
        </footer>
        <script src="Js/script.js"></script>

    </body>
</html>